### ISSUE TITLE
<a> tags should keep their colors when no href attribute

### ISSUE THREAD

**Issue by pellenberger** [alv-ch/styleguide#19]
When removing _href_ attribute on a _<a>_ HTML tag, the color of the link changes. 
It is due to this rule : 
```
a:not([href]):not([tabindex]) {
  color: inherit;
  text-decoration: none; 
}
```
Remove the _color: inherit_ rule in order to fix this bug.

**Comment by tdascoli** [comment]
Fixed

**Comment by tdascoli** [comment]
add cursor pointer and hover effect
